# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 05:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalfilename', models.CharField(max_length=256, verbose_name='Original Filename')),
                ('afile', models.FileField(upload_to='attachments/', verbose_name='File')),
            ],
        ),
        migrations.CreateModel(
            name='FilePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pprovnum', models.CharField(max_length=6)),
                ('pfye', models.DateField()),
                ('ptitle', models.TextField()),
                ('pdescription', models.TextField()),
                ('accessiblebygroups', models.ManyToManyField(to='auth.Group')),
                ('accessiblebyusers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('fileattachments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snailfile.FileAttachment')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagtext', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='filepackage',
            name='tags',
            field=models.ManyToManyField(to='snailfile.Tag'),
        ),
    ]
