# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snailfile', '0002_auto_20170831_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepackage',
            name='fileattachments',
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='filepackage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='snailfile.FilePackage'),
            preserve_default=False,
        ),
    ]
