# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 01:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snailfile', '0003_auto_20170901_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepackage',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='createdfp', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filepackage',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filepackage',
            name='accessiblebyusers',
            field=models.ManyToManyField(related_name='accessiblefp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filepackage',
            name='pdescription',
            field=models.TextField(verbose_name='Package Description'),
        ),
        migrations.AlterField(
            model_name='filepackage',
            name='pfye',
            field=models.DateField(verbose_name='Fiscal Year End'),
        ),
        migrations.AlterField(
            model_name='filepackage',
            name='pprovnum',
            field=models.CharField(max_length=6, verbose_name='Provider Number'),
        ),
        migrations.AlterField(
            model_name='filepackage',
            name='ptitle',
            field=models.TextField(verbose_name='Package Title'),
        ),
    ]
