# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snailfile', '0004_auto_20170905_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepackage',
            name='ptitle',
            field=models.CharField(max_length=255, verbose_name='Package Title'),
        ),
    ]
